#!/usr/bin/env python

Import("env")

env_ex = env.Clone()

source_dirs = [
    "./algorithm/*.cpp",
    "./algorithm/noise/basic_noise.cpp",
    "./algorithm/noise/improved_perlin_noise.cpp",
    "./algorithm/noise/open_simplex.cpp",
    "./data_structure/*.cpp",
    "./math/*.cpp",
    "./*.cpp"
]

for dir in source_dirs:
    env_ex.add_source_files(env.modules_sources, dir)
